use characteristics::Characteristic;
use skills::Skill;

pub struct Career<'a> {
    pub name: &'a str,
    qualifications: (Characteristic, u8),
    survival: (Characteristic, u8),
    commission: Option<(Characteristic, u8)>,
    advancement: Option<(Characteristic, u8)>,
    reenlistment: u8,
    ranks: Vec<(Option<&'static str>, Option<Skill>)>,
    material_benefits: Vec<MaterialBenefit>,
    cash_benefits: Vec<u32>,
    personal_development: Vec<Training>,
    service_skills: Vec<Training>,
    specialist: Vec<Training>,
    advanced_education: Vec<Training>,
}

pub enum MaterialBenefit {
    MBC(Characteristic),
    CourierVessel,
    ExplorersSociety,
    HighPassage,
    LowPassage,
    MidPassage,
    ResearchVessel,
    ShipShares,
    Weapon,
}

pub enum Training {
    TC(Characteristic),
    TS(Skill),
}


pub fn careers<'a>() -> Vec<Career<'a>> {
    use self::MaterialBenefit::*;
    use self::Training::*;
    use characteristics::Characteristic::*;
    use skills::Skill::*;

    vec![
        Career {
            name: "Athlete",
            qualifications: (Endurance, 8),
            survival: (Dexterity, 5),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Athletics))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                ExplorersSociety,
                HighPassage,
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Intelligence),
                TC(Education),
                TC(Social),
                TS(Carousing),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Athletics),
                TS(Admin),
                TS(Carousing),
                TS(Computer),
                TS(Gambling),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(ZeroG),
                TS(Athletics),
                TS(Athletics),
                TS(Computer),
                TS(Leadership),
                TS(Gambling),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Aerospace Defense",
            qualifications: (Endurance, 5),
            survival: (Dexterity, 5),
            commission: Some((Education, 6)),
            advancement: Some((Education, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Airman"), Some(Aircraft)),
                (Some("Flight Officer"), None),
                (Some("Flight Lieutenant"), None),
                (Some("Squadron Leader"), Some(Leadership)),
                (Some("Wing Commander"), None),
                (Some("Group Captain"), None),
                (Some("Air Commodore"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                Weapon,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(Athletics),
                TS(MeleeCombat),
                TS(Vehicle),
            ],
            service_skills: vec![
                TS(Electronics),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Survival),
                TS(Aircraft),
            ],
            specialist: vec![
                TS(Comms),
                TS(Gravitics),
                TS(GunCombat),
                TS(Gunnery),
                TS(Recon),
                TS(Piloting),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
            ],
        },
        Career {
            name: "Agent",
            qualifications: (Social, 6),
            survival: (Intelligence, 6),
            commission: Some((Education, 7)),
            advancement: Some((Education, 6)),
            reenlistment: 6,
            ranks: vec![
                (Some("Agent"), Some(Streetwise)),
                (Some("Special Agent"), None),
                (Some("Sp Agent in Charge"), None),
                (Some("Unit Chief"), Some(Leadership)),
                (Some("Section Chief"), Some(Admin)),
                (Some("Assistant Director"), None),
                (Some("Director"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Streetwise),
                TS(Bribery),
                TS(Leadership),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Leadership),
                TS(Recon),
                TS(Survival),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
            ],
        },
        Career {
            name: "Barbarian",
            qualifications: (Endurance, 5),
            survival: (Strength, 6),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![(None, Some(MeleeCombat))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                Weapon,
                MBC(Endurance),
                MidPassage,
            ],
            cash_benefits: vec![0, 1000, 2000, 5000, 5000, 10000, 10000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Survival),
                TS(Animals),
            ],
            specialist: vec![
                TS(GunCombat),
                TS(JackOfAllTrades),
                TS(MeleeCombat),
                TS(Recon),
                TS(Animals),
                TS(Tactics),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
                TS(Broker),
            ],
        },
        Career {
            name: "Belter",
            qualifications: (Intelligence, 4),
            survival: (Dexterity, 7),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![(None, Some(ZeroG))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                ShipShares,
                HighPassage,
            ],
            cash_benefits: vec![1000, 5000, 5000, 5000, 10000, 20000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(ZeroG),
                TS(MeleeCombat),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Demolitions),
                TS(GunCombat),
                TS(Gunnery),
                TS(Prospecting),
                TS(Piloting),
            ],
            specialist: vec![
                TS(ZeroG),
                TS(Computer),
                TS(Electronics),
                TS(Prospecting),
                TS(Sciences),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Engineering),
                TS(Medicine),
                TS(Navigation),
                TS(Comms),
                TS(Tactics),
            ],
        },
        Career {
            name: "Bureaucrat",
            qualifications: (Social, 6),
            survival: (Education, 4),
            commission: Some((Social, 5)),
            advancement: Some((Intelligence, 8)),
            reenlistment: 5,
            ranks: vec![
                (Some("Assistant"), Some(Admin)),
                (Some("Clerk"), None),
                (Some("Supervisor"), None),
                (Some("Manager"), None),
                (Some("Chief"), None),
                (Some("Director"), None),
                (Some("Minister"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Intelligence),
                MidPassage,
                MidPassage,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Leadership),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Admin),
                TS(Computer),
                TS(Perception),
                TS(Leadership),
                TS(Steward),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Admin),
            ],
        },
        Career {
            name: "Colonist",
            qualifications: (Endurance, 5),
            survival: (Endurance, 6),
            commission: Some((Intelligence, 7)),
            advancement: Some((Education, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Citizen"), Some(Survival)),
                (Some("District Leader"), None),
                (Some("District Delegate"), None),
                (Some("Council Advisor"), Some(Liaison)),
                (Some("Councilor"), None),
                (Some("Lieutenant Governor"), None),
                (Some("Governor"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                MidPassage,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 5000, 5000, 10000, 20000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(Animals),
                TS(Electronics),
                TS(Survival),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Athletics),
                TS(Carousing),
                TS(JackOfAllTrades),
                TS(Engineering),
                TS(Animals),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Liaison),
                TS(Admin),
                TS(Animals),
            ],
        },
        Career {
            name: "Diplomat",
            qualifications: (Social, 6),
            survival: (Education, 5),
            commission: Some((Intelligence, 7)),
            advancement: Some((Social, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Attaché"), Some(Liaison)),
                (Some("Third Secretary"), None),
                (Some("Second Secretary"), None),
                (Some("First Secretary"), Some(Admin)),
                (Some("Counselor"), None),
                (Some("Minister"), None),
                (Some("Ambassador"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MidPassage,
                HighPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Liaison),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Carousing),
                TS(Linguistics),
                TS(Bribery),
                TS(Liaison),
                TS(Steward),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
            ],
        },
        Career {
            name: "Drifter",
            qualifications: (Dexterity, 5),
            survival: (Endurance, 5),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                Weapon,
                MidPassage,
                MidPassage,
            ],
            cash_benefits: vec![0, 1000, 2000, 5000, 5000, 10000, 10000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Streetwise),
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Electronics),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Streetwise),
                TS(Gambling),
                TS(Recon),
            ],
            advanced_education: vec![
                TS(Computer),
                TS(Engineering),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Liaison),
                TS(Tactics),
            ],
        },
        Career {
            name: "Entertainer",
            qualifications: (Social, 5),
            survival: (Intelligence, 5),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Carousing))],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Social),
                HighPassage,
                ExplorersSociety,
                HighPassage,
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Intelligence),
                TC(Education),
                TC(Social),
                TS(Carousing),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Athletics),
                TS(Admin),
                TS(Carousing),
                TS(Bribery),
                TS(Gambling),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Liaison),
                TS(Gambling),
                TS(Recon),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Carousing),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Hunter",
            qualifications: (Endurance, 5),
            survival: (Strength, 8),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Survival))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                ShipShares,
                HighPassage,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Survival),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Admin),
                TS(Comms),
                TS(Electronics),
                TS(Recon),
                TS(Animals),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Liaison),
                TS(Tactics),
                TS(Animals),
            ],
        },
        Career {
            name: "Marine",
            qualifications: (Intelligence, 6),
            survival: (Endurance, 6),
            commission: Some((Education, 6)),
            advancement: Some((Social, 7)),
            reenlistment: 6,
            ranks: vec![
                (Some("Trooper"), Some(ZeroG)),
                (Some("Lieutenant"), None),
                (Some("Captain"), None),
                (Some("Major"), Some(Tactics)),
                (Some("Lt Colonel"), None),
                (Some("Colonel"), None),
                (Some("Brigadier"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Demolitions),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(BattleDress),
            ],
            specialist: vec![
                TS(Electronics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Survival),
                TS(Recon),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Gravitics),
                TS(Medicine),
                TS(Navigation),
                TS(Tactics),
            ],
        },
    ]
}
