use characteristics::Characteristic;
use skills::Skill;

pub struct Career {
    pub name: &'static str,
    pub qualifications: (Characteristic, u8),
    pub survival: (Characteristic, u8),
    pub commission: Option<(Characteristic, u8)>,
    pub advancement: Option<(Characteristic, u8)>,
    pub reenlistment: u8,
    pub ranks: Vec<(Option<&'static str>, Option<Skill>)>,
    pub material_benefits: Vec<MaterialBenefit>,
    pub cash_benefits: Vec<u32>,
    pub personal_development: Vec<Training>,
    pub service_skills: Vec<Training>,
    pub specialist: Vec<Training>,
    pub advanced_education: Vec<Training>,
}

#[derive(Debug)]
pub enum MaterialBenefit {
    MBC(Characteristic),
    CourierVessel,
    ExplorersSociety,
    HighPassage,
    LowPassage,
    MidPassage,
    ResearchVessel,
    ShipShares,
    Weapon,
}

pub enum Training {
    TC(Characteristic),
    TS(Skill),
}


pub fn careers() -> Vec<Career> {
    use self::MaterialBenefit::*;
    use self::Training::*;
    use characteristics::Characteristic::*;
    use skills::Skill::*;

    vec![
        Career {
            name: "Athlete",
            qualifications: (Endurance, 8),
            survival: (Dexterity, 5),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Athletics))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                ExplorersSociety,
                HighPassage,
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Intelligence),
                TC(Education),
                TC(Social),
                TS(Carousing),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Athletics),
                TS(Admin),
                TS(Carousing),
                TS(Computer),
                TS(Gambling),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(ZeroG),
                TS(Athletics),
                TS(Athletics),
                TS(Computer),
                TS(Leadership),
                TS(Gambling),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Aerospace Defense",
            qualifications: (Endurance, 5),
            survival: (Dexterity, 5),
            commission: Some((Education, 6)),
            advancement: Some((Education, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Airman"), Some(Aircraft)),
                (Some("Flight Officer"), None),
                (Some("Flight Lieutenant"), None),
                (Some("Squadron Leader"), Some(Leadership)),
                (Some("Wing Commander"), None),
                (Some("Group Captain"), None),
                (Some("Air Commodore"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                Weapon,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(Athletics),
                TS(MeleeCombat),
                TS(Vehicle),
            ],
            service_skills: vec![
                TS(Electronics),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Survival),
                TS(Aircraft),
            ],
            specialist: vec![
                TS(Comms),
                TS(Gravitics),
                TS(GunCombat),
                TS(Gunnery),
                TS(Recon),
                TS(Piloting),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
            ],
        },
        Career {
            name: "Agent",
            qualifications: (Social, 6),
            survival: (Intelligence, 6),
            commission: Some((Education, 7)),
            advancement: Some((Education, 6)),
            reenlistment: 6,
            ranks: vec![
                (Some("Agent"), Some(Streetwise)),
                (Some("Special Agent"), None),
                (Some("Sp Agent in Charge"), None),
                (Some("Unit Chief"), Some(Leadership)),
                (Some("Section Chief"), Some(Admin)),
                (Some("Assistant Director"), None),
                (Some("Director"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Streetwise),
                TS(Bribery),
                TS(Leadership),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Leadership),
                TS(Recon),
                TS(Survival),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
            ],
        },
        Career {
            name: "Barbarian",
            qualifications: (Endurance, 5),
            survival: (Strength, 6),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![(None, Some(MeleeCombat))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                Weapon,
                MBC(Endurance),
                MidPassage,
            ],
            cash_benefits: vec![0, 1000, 2000, 5000, 5000, 10000, 10000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Survival),
                TS(Animals),
            ],
            specialist: vec![
                TS(GunCombat),
                TS(JackOfAllTrades),
                TS(MeleeCombat),
                TS(Recon),
                TS(Animals),
                TS(Tactics),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
                TS(Broker),
            ],
        },
        Career {
            name: "Belter",
            qualifications: (Intelligence, 4),
            survival: (Dexterity, 7),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![(None, Some(ZeroG))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                ShipShares,
                HighPassage,
            ],
            cash_benefits: vec![1000, 5000, 5000, 5000, 10000, 20000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(ZeroG),
                TS(MeleeCombat),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Demolitions),
                TS(GunCombat),
                TS(Gunnery),
                TS(Prospecting),
                TS(Piloting),
            ],
            specialist: vec![
                TS(ZeroG),
                TS(Computer),
                TS(Electronics),
                TS(Prospecting),
                TS(Sciences),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Engineering),
                TS(Medicine),
                TS(Navigation),
                TS(Comms),
                TS(Tactics),
            ],
        },
        Career {
            name: "Bureaucrat",
            qualifications: (Social, 6),
            survival: (Education, 4),
            commission: Some((Social, 5)),
            advancement: Some((Intelligence, 8)),
            reenlistment: 5,
            ranks: vec![
                (Some("Assistant"), Some(Admin)),
                (Some("Clerk"), None),
                (Some("Supervisor"), None),
                (Some("Manager"), None),
                (Some("Chief"), None),
                (Some("Director"), None),
                (Some("Minister"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Intelligence),
                MidPassage,
                MidPassage,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Leadership),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Admin),
                TS(Computer),
                TS(Perception),
                TS(Leadership),
                TS(Steward),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Admin),
            ],
        },
        Career {
            name: "Colonist",
            qualifications: (Endurance, 5),
            survival: (Endurance, 6),
            commission: Some((Intelligence, 7)),
            advancement: Some((Education, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Citizen"), Some(Survival)),
                (Some("District Leader"), None),
                (Some("District Delegate"), None),
                (Some("Council Advisor"), Some(Liaison)),
                (Some("Councilor"), None),
                (Some("Lieutenant Governor"), None),
                (Some("Governor"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                MidPassage,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 5000, 5000, 10000, 20000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(Animals),
                TS(Electronics),
                TS(Survival),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Athletics),
                TS(Carousing),
                TS(JackOfAllTrades),
                TS(Engineering),
                TS(Animals),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Liaison),
                TS(Admin),
                TS(Animals),
            ],
        },
        Career {
            name: "Diplomat",
            qualifications: (Social, 6),
            survival: (Education, 5),
            commission: Some((Intelligence, 7)),
            advancement: Some((Social, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Attaché"), Some(Liaison)),
                (Some("Third Secretary"), None),
                (Some("Second Secretary"), None),
                (Some("First Secretary"), Some(Admin)),
                (Some("Counselor"), None),
                (Some("Minister"), None),
                (Some("Ambassador"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MidPassage,
                HighPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(Athletics),
                TS(Carousing),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Liaison),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Carousing),
                TS(Linguistics),
                TS(Bribery),
                TS(Liaison),
                TS(Steward),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Leadership),
            ],
        },
        Career {
            name: "Drifter",
            qualifications: (Dexterity, 5),
            survival: (Endurance, 5),
            commission: None,
            advancement: None,
            reenlistment: 5,
            ranks: vec![],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                Weapon,
                MidPassage,
                MidPassage,
            ],
            cash_benefits: vec![0, 1000, 2000, 5000, 5000, 10000, 10000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Streetwise),
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Electronics),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Streetwise),
                TS(Gambling),
                TS(Recon),
            ],
            advanced_education: vec![
                TS(Computer),
                TS(Engineering),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Liaison),
                TS(Tactics),
            ],
        },
        Career {
            name: "Entertainer",
            qualifications: (Social, 5),
            survival: (Intelligence, 5),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Carousing))],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Social),
                HighPassage,
                ExplorersSociety,
                HighPassage,
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 100000],
            personal_development: vec![
                TC(Dexterity),
                TC(Intelligence),
                TC(Education),
                TC(Social),
                TS(Carousing),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Athletics),
                TS(Admin),
                TS(Carousing),
                TS(Bribery),
                TS(Gambling),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Computer),
                TS(Carousing),
                TS(Bribery),
                TS(Liaison),
                TS(Gambling),
                TS(Recon),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Carousing),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Hunter",
            qualifications: (Endurance, 5),
            survival: (Strength, 8),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Survival))],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                ShipShares,
                HighPassage,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TS(Athletics),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Survival),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Admin),
                TS(Comms),
                TS(Electronics),
                TS(Recon),
                TS(Animals),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Linguistics),
                TS(Medicine),
                TS(Liaison),
                TS(Tactics),
                TS(Animals),
            ],
        },
        Career {
            name: "Marine",
            qualifications: (Intelligence, 6),
            survival: (Endurance, 6),
            commission: Some((Education, 6)),
            advancement: Some((Social, 7)),
            reenlistment: 6,
            ranks: vec![
                (Some("Trooper"), Some(ZeroG)),
                (Some("Lieutenant"), None),
                (Some("Captain"), None),
                (Some("Major"), Some(Tactics)),
                (Some("Lt Colonel"), None),
                (Some("Colonel"), None),
                (Some("Brigadier"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Demolitions),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(BattleDress),
            ],
            specialist: vec![
                TS(Electronics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Survival),
                TS(Recon),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Gravitics),
                TS(Medicine),
                TS(Navigation),
                TS(Tactics),
            ],
        },
        Career {
            name: "Maritime Defense",
            qualifications: (Endurance, 5),
            survival: (Endurance, 5),
            commission: Some((Intelligence, 6)),
            advancement: Some((Education, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Seaman"), Some(Watercraft)),
                (Some("Ensign"), None),
                (Some("Lieutenant"), None),
                (Some("Lt Commander"), Some(Leadership)),
                (Some("Commander"), None),
                (Some("Captain"), None),
                (Some("Admiral"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                Weapon,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(Athletics),
                TS(MeleeCombat),
                TS(Vehicle),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Survival),
                TS(Watercraft),
            ],
            specialist: vec![
                TS(Comms),
                TS(Electronics),
                TS(GunCombat),
                TS(Demolitions),
                TS(Recon),
                TS(Watercraft),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
            ],
        },
        Career {
            name: "Mercenary",
            qualifications: (Intelligence, 4),
            survival: (Endurance, 6),
            commission: Some((Intelligence, 7)),
            advancement: Some((Intelligence, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Private"), Some(GunCombat)),
                (Some("Lieutenant"), None),
                (Some("Captain"), None),
                (Some("Major"), Some(Tactics)),
                (Some("Lt Colonel"), None),
                (Some("Colonel"), None),
                (Some("Brigadier"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                MBC(Social),
                HighPassage,
                ShipShares,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(ZeroG),
                TS(MeleeCombat),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Gambling),
                TS(BattleDress),
            ],
            specialist: vec![
                TS(Gravitics),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Recon),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Engineering),
                TS(Medicine),
                TS(Navigation),
                TS(Sciences),
                TS(Tactics),
            ],
        },
        Career {
            name: "Merchant",
            qualifications: (Intelligence, 4),
            survival: (Intelligence, 5),
            commission: Some((Intelligence, 5)),
            advancement: Some((Education, 8)),
            reenlistment: 4,
            ranks: vec![
                (Some("Crewman"), Some(Steward)),
                (Some("Deck Cadet"), None),
                (Some("Fourth Officer"), None),
                (Some("Third Officer"), Some(Piloting)),
                (Some("Second Officer"), None),
                (Some("First Officer"), None),
                (Some("Captain"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                HighPassage,
                ShipShares,
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(ZeroG),
                TS(MeleeCombat),
                TS(Steward),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Engineering),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Broker),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Carousing),
                TS(Gunnery),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Navigation),
                TS(Piloting),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Engineering),
                TS(Medicine),
                TS(Navigation),
                TS(Sciences),
                TS(Tactics),
            ],
        },
        Career {
            name: "Navy",
            qualifications: (Intelligence, 6),
            survival: (Intelligence, 5),
            commission: Some((Social, 7)),
            advancement: Some((Education, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Starman"), Some(ZeroG)),
                (Some("Midshipman"), None),
                (Some("Lieutenant"), None),
                (Some("Lt Commander"), Some(Tactics)),
                (Some("Commander"), None),
                (Some("Captain"), None),
                (Some("Commodore"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                MBC(Social),
                HighPassage,
                ExplorersSociety,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Engineering),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Gravitics),
                TS(JackOfAllTrades),
                TS(MeleeCombat),
                TS(Navigation),
                TS(Leadership),
                TS(Piloting),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Engineering),
                TS(Medicine),
                TS(Navigation),
                TS(Tactics),
            ],
        },
        Career {
            name: "Noble",
            qualifications: (Social, 8),
            survival: (Social, 4),
            commission: Some((Education, 5)),
            advancement: Some((Intelligence, 8)),
            reenlistment: 6,
            ranks: vec![
                (Some("Courtier"), Some(Carousing)),
                (Some("Knight"), None),
                (Some("Baron"), None),
                (Some("Marquis"), None),
                (Some("Count"), Some(Advocate)),
                (Some("Duke"), None),
                (Some("Archduke"), None),
            ],
            material_benefits: vec![
                HighPassage,
                MBC(Education),
                MBC(Intelligence),
                HighPassage,
                ExplorersSociety,
                HighPassage,
                ShipShares,
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 50000],
            personal_development: vec![
                TC(Dexterity),
                TC(Intelligence),
                TC(Education),
                TC(Social),
                TS(Carousing),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Athletics),
                TS(Admin),
                TS(Carousing),
                TS(Leadership),
                TS(Gambling),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Computer),
                TS(Carousing),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Liaison),
                TS(Animals),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Liaison),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Physician",
            qualifications: (Education, 6),
            survival: (Intelligence, 4),
            commission: Some((Intelligence, 5)),
            advancement: Some((Education, 8)),
            reenlistment: 5,
            ranks: vec![
                (Some("Intern"), Some(Medicine)),
                (Some("Resident"), None),
                (Some("Senior Resident"), None),
                (Some("Chief Resident"), None),
                (Some("Attending Phys."), Some(Admin)),
                (Some("Service Chief"), None),
                (Some("Hospital Admin."), None),
            ],
            material_benefits: vec![
                HighPassage,
                MBC(Education),
                MBC(Intelligence),
                HighPassage,
                ExplorersSociety,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![2000, 10000, 20000, 20000, 50000, 100000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Mechanics),
                TS(Medicine),
                TS(Leadership),
                TS(Sciences),
            ],
            specialist: vec![
                TS(Computer),
                TS(Carousing),
                TS(Electronics),
                TS(Medicine),
                TS(Medicine),
                TS(Sciences),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Pirate",
            qualifications: (Dexterity, 5),
            survival: (Dexterity, 6),
            commission: Some((Strength, 7)),
            advancement: Some((Intelligence, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Crewman"), Some(Gunnery)),
                (Some("Corporal"), None),
                (Some("Lieutenant"), Some(Piloting)),
                (Some("Lt Commander"), None),
                (Some("Commander"), None),
                (Some("Captain"), None),
                (Some("Commodore"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                HighPassage,
                MBC(Social),
                HighPassage,
                ShipShares,
            ],
            cash_benefits: vec![1000, 5000, 10000, 20000, 20000, 50000, 100000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Streetwise),
                TS(Electronics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(ZeroG),
                TS(Comms),
                TS(Engineering),
                TS(Gunnery),
                TS(Navigation),
                TS(Piloting),
            ],
            advanced_education: vec![
                TS(Computer),
                TS(Gravitics),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Advocate),
                TS(Tactics),
            ],
        },
        Career {
            name: "Rogue",
            qualifications: (Dexterity, 5),
            survival: (Dexterity, 4),
            commission: Some((Strength, 6)),
            advancement: Some((Intelligence, 7)),
            reenlistment: 4,
            ranks: vec![
                (Some("Independent"), Some(Streetwise)),
                (Some("Associate"), None),
                (Some("Soldier"), Some(GunCombat)),
                (Some("Lieutenant"), None),
                (Some("Underboss"), None),
                (Some("Consigliere"), None),
                (Some("Boss"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                Weapon,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 5000, 5000, 10000, 20000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(MeleeCombat),
                TS(Bribery),
                TS(Gambling),
            ],
            service_skills: vec![
                TS(Streetwise),
                TS(Mechanics),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Recon),
                TS(Vehicle),
            ],
            specialist: vec![
                TS(Computer),
                TS(Electronics),
                TS(Bribery),
                TS(Broker),
                TS(Recon),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Computer),
                TS(Gravitics),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Advocate),
                TS(Tactics),
            ],
        },
        Career {
            name: "Scientist",
            qualifications: (Education, 5),
            survival: (Education, 5),
            commission: Some((Intelligence, 7)),
            advancement: Some((Intelligence, 6)),
            reenlistment: 5,
            ranks: vec![
                (Some("Instructor"), Some(Streetwise)),
                (Some("Adjunct Professor"), None),
                (Some("Research Professor"), Some(GunCombat)),
                (Some("Assistant Professor"), None),
                (Some("Associate Professor"), None),
                (Some("Professor"), None),
                (Some("Distinguished Professor"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Intelligence),
                MidPassage,
                MBC(Social),
                HighPassage,
                ResearchVessel,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Electronics),
                TS(Medicine),
                TS(Bribery),
                TS(Sciences),
            ],
            specialist: vec![
                TS(Navigation),
                TS(Admin),
                TS(Sciences),
                TS(Sciences),
                TS(Animals),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
        Career {
            name: "Scout",
            qualifications: (Intelligence, 6),
            survival: (Endurance, 7),
            commission: None,
            advancement: None,
            reenlistment: 6,
            ranks: vec![(None, Some(Piloting))],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                Weapon,
                MidPassage,
                ExplorersSociety,
                CourierVessel,
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(JackOfAllTrades),
                TC(Education),
                TS(MeleeCombat),
            ],
            service_skills: vec![
                TS(Comms),
                TS(Electronics),
                TS(GunCombat),
                TS(Gunnery),
                TS(Recon),
                TS(Piloting),
            ],
            specialist: vec![
                TS(Engineering),
                TS(Gunnery),
                TS(Demolitions),
                TS(Navigation),
                TS(Medicine),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(Linguistics),
                TS(Medicine),
                TS(Navigation),
                TS(Tactics),
            ],
        },
        Career {
            name: "Surface Defense",
            qualifications: (Endurance, 5),
            survival: (Education, 5),
            commission: Some((Endurance, 6)),
            advancement: Some((Education, 7)),
            reenlistment: 5,
            ranks: vec![
                (Some("Private"), Some(Piloting)),
                (Some("Lieutenant"), None),
                (Some("Captain"), None),
                (Some("Major"), Some(Leadership)),
                (Some("Lt Colonel"), None),
                (Some("Colonel"), None),
                (Some("General"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Intelligence),
                Weapon,
                MidPassage,
                Weapon,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TS(Athletics),
                TS(MeleeCombat),
                TS(Vehicle),
            ],
            service_skills: vec![
                TS(Mechanics),
                TS(GunCombat),
                TS(Gunnery),
                TS(MeleeCombat),
                TS(Recon),
                TS(BattleDress),
            ],
            specialist: vec![
                TS(Comms),
                TS(Demolitions),
                TS(GunCombat),
                TS(MeleeCombat),
                TS(Survival),
                TS(Vehicle),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Medicine),
                TS(Leadership),
                TS(Tactics),
            ],
        },
        Career {
            name: "Technician",
            qualifications: (Education, 6),
            survival: (Dexterity, 4),
            commission: Some((Education, 5)),
            advancement: Some((Intelligence, 8)),
            reenlistment: 5,
            ranks: vec![
                (Some("Technician"), Some(Computer)),
                (Some("Team Lead"), None),
                (Some("Supervisor"), None),
                (Some("Manager"), None),
                (Some("Director"), Some(Admin)),
                (Some("Vice-President"), None),
                (Some("Executive Officer"), None),
            ],
            material_benefits: vec![
                LowPassage,
                MBC(Education),
                MBC(Intelligence),
                MidPassage,
                MidPassage,
                HighPassage,
                MBC(Social),
            ],
            cash_benefits: vec![1000, 5000, 10000, 10000, 20000, 50000, 50000],
            personal_development: vec![
                TC(Strength),
                TC(Dexterity),
                TC(Endurance),
                TC(Intelligence),
                TC(Education),
                TS(GunCombat),
            ],
            service_skills: vec![
                TS(Admin),
                TS(Computer),
                TS(Mechanics),
                TS(Medicine),
                TS(Electronics),
                TS(Sciences),
            ],
            specialist: vec![
                TS(Computer),
                TS(Electronics),
                TS(Gravitics),
                TS(Linguistics),
                TS(Engineering),
                TS(Animals),
            ],
            advanced_education: vec![
                TS(Advocate),
                TS(Computer),
                TS(JackOfAllTrades),
                TS(Linguistics),
                TS(Medicine),
                TS(Sciences),
            ],
        },
    ]
}
