use std::collections::HashMap;

pub trait Skills {
    fn skills(&self) -> Vec<Skill>;
}

fn education_skills() -> Vec<Skill> {
    use skills::Skill::*;
    vec![Admin,
         Advocate,
         Animals,
         Carousing,
         Comms,
         Computer,
         Electronics,
         Engineering,
         LifeSciences,
         Linguistics,
         Mechanics,
         Medicine,
         PhysicalSciences,
         SocialSciences,
         SpaceSciences]
}

struct CharacterSkills {
    pub entity_id: u32,
    pub skills: HashMap<Skill, u8>,
}

pub enum Skill {
    Admin,
    Advocate,
    Animals,
    Farming,
    Riding,
    Survival,
    VeterinaryMedicine,
    Athletics,
    BattleDress,
    Bribery,
    Broker,
    Carousing,
    Comms,
    Computer,
    Demolitions,
    Electronics,
    Engineering,
    Gambling,
    Gravitics,
    JackOfAllTrades,
    Leadership,
    Linguistics,
    Liaison,
    Mechanics,
    Medicine,
    Navigation,
    Piloting,
    Recon,
    Sciences,
    LifeSciences,
    PhysicalSciences,
    SocialSciences,
    SpaceSciences,
    Steward,
    Streetwise,
    Tactics,
    ZeroG,
    GunCombat,
    Archery,
    EnergyPistol,
    EnergyRifle,
    Shotgun,
    SlugPistol,
    SlugRifle,
    Gunnery,
    BayWeapons,
    HeavyWeapons,
    Screens,
    SpinalMounts,
    TurretWeapons,
    MeleeCombat,
    BludgeoningWeapons,
    NaturalWeapons,
    PiercingWeapons,
    SlashingWeapons,
    Vehicle,
    Aircraft,
    GravVehicle,
    RotorAircraft,
    WingedAircraft,
    Mole,
    TrackedVehicle,
    Watercraft,
    Motorboats,
    OceanShips,
    SailingShips,
    Submarine,
    WheeledVehicle,
}